### ISSUE TITLE
Build errors for 32bit target

### ISSUE THREAD

**Issue by admaunaloa** [sjames/cyclonedds-rs#1]
When building on Raspberry PI with the standard (Raspberry Pi OS with desktop) i get the following errors:

 Compiling cdds_derive v0.1.0 (/home/pi/Documents/cyclonedds-rs/dds_derive)
   Compiling thiserror v1.0.30
   Compiling cyclonedds-sys v0.1.2 (/home/pi/Documents/cyclonedds-sys)
   Compiling cyclonedds-rs v0.3.1 (/home/pi/Documents/cyclonedds-rs)
error[E0308]: mismatched types
   --> src/dds_reader.rs:207:73
    |
207 |                 dds_take(entity.entity(), voidpp ,  info_ptr as *mut _, buf.len() as u64, buf.len() as u32)
    |                                                                         ^^^^^^^^^^^^^^^^ expected `u32`, found `u64`
    |
help: you can convert a `u64` to a `u32` and panic if the converted value doesn't fit
    |
207 |                 dds_take(entity.entity(), voidpp ,  info_ptr as *mut _, (buf.len() as u64).try_into().unwrap(), buf.len() as u32)
    |                                                                         +                +++++++++++++++++++++

error[E0308]: mismatched types
   --> src/dds_reader.rs:209:73
    |
209 |                 dds_read(entity.entity(), voidpp ,  info_ptr as *mut _, buf.len() as u64, buf.len() as u32)
    |                                                                         ^^^^^^^^^^^^^^^^ expected `u32`, found `u64`
    |
help: you can convert a `u64` to a `u32` and panic if the converted value doesn't fit
    |
209 |                 dds_read(entity.entity(), voidpp ,  info_ptr as *mut _, (buf.len() as u64).try_into().unwrap(), buf.len() as u32)
    |                                                                         +                +++++++++++++++++++++

error[E0308]: mismatched types
  --> src/dds_waitset.rs:80:17
   |
80 |                 capacity as u64,
   |                 ^^^^^^^^^^^^^^^ expected `u32`, found `u64`
   |
help: you can convert a `u64` to a `u32` and panic if the converted value doesn't fit
   |
80 |                 (capacity as u64).try_into().unwrap(),
   |                 +               +++++++++++++++++++++

error[E0308]: mismatched types
   --> src/serdes.rs:635:27
    |
635 |             iov.iov_len = serdata.key_hash.len() as u64;
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `u64`

error[E0308]: mismatched types
   --> src/serdes.rs:663:31
    |
663 |                 iov.iov_len = cdr.len() as u64;
    |                               ^^^^^^^^^^^^^^^^ expected `u32`, found `u64`

error[E0308]: mismatched types
   --> src/serdes.rs:773:28
    |
773 |         zero_samples: Some(zero_samples::<T>),
    |                            ^^^^^^^^^^^^^^^^^ expected `u32`, found `u64`
    |
    = note: expected fn pointer `unsafe extern "C" fn(_, _, u32)`
                  found fn item `unsafe extern "C" fn(_, _, u64) {zero_samples::<T>}`

error[E0308]: mismatched types
   --> src/serdes.rs:774:31
    |
774 |         realloc_samples: Some(realloc_samples::<T>),
    |                               ^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `u64`
    |
    = note: expected fn pointer `unsafe extern "C" fn(_, _, _, u32, u32)`
                  found fn item `extern "C" fn(_, _, _, u64, u64) {realloc_samples::<T>}`

error[E0308]: mismatched types
   --> src/serdes.rs:775:28
    |
775 |         free_samples: Some(free_samples::<T>),
    |                            ^^^^^^^^^^^^^^^^^ expected `u32`, found `u64`
    |
    = note: expected fn pointer `unsafe extern "C" fn(_, _, u32, _)`
                  found fn item `extern "C" fn(_, _, u64, _) {free_samples::<T>}`

error[E0560]: struct `cyclonedds_sys::ddsi_sertype_ops` has no field named `typeid_hash`
   --> src/serdes.rs:778:9
    |
778 |         typeid_hash: None,
    |         ^^^^^^^^^^^ `cyclonedds_sys::ddsi_sertype_ops` does not have this field
    |
    = note: available fields are: `version`, `arg`, `free`, `zero_samples`, `realloc_samples` ... and 10 others

error[E0560]: struct `cyclonedds_sys::ddsi_sertype_ops` has no field named `serialized_size`
   --> src/serdes.rs:779:9
    |
779 |         serialized_size: None,
    |         ^^^^^^^^^^^^^^^ help: a field with a similar name exists: `get_serialized_size`

error[E0560]: struct `cyclonedds_sys::ddsi_sertype_ops` has no field named `serialize`
   --> src/serdes.rs:780:9
    |
780 |         serialize: None,
    |         ^^^^^^^^^ `cyclonedds_sys::ddsi_sertype_ops` does not have this field
    |
    = note: available fields are: `version`, `arg`, `free`, `zero_samples`, `realloc_samples` ... and 10 others

error[E0560]: struct `cyclonedds_sys::ddsi_sertype_ops` has no field named `deserialize`
   --> src/serdes.rs:781:9
    |
781 |         deserialize: None,
    |         ^^^^^^^^^^^ `cyclonedds_sys::ddsi_sertype_ops` does not have this field
    |
    = note: available fields are: `version`, `arg`, `free`, `zero_samples`, `realloc_samples` ... and 10 others

error[E0308]: mismatched types
   --> src/serdes.rs:793:24
    |
793 |         from_ser: Some(serdata_from_fragchain::<T>),
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `u64`
    |
    = note: expected fn pointer `unsafe extern "C" fn(_, _, _, u32) -> _`
                  found fn item `unsafe extern "C" fn(_, _, _, u64) -> _ {serdata_from_fragchain::<T>}`

error[E0308]: mismatched types
   --> src/serdes.rs:794:28
    |
794 |         from_ser_iov: Some(serdata_from_iov::<T>),
    |                            ^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `u64`
    |
    = note: expected fn pointer `unsafe extern "C" fn(_, _, u32, _, u32) -> _`
                  found fn item `unsafe extern "C" fn(_, _, u64, _, u64) -> _ {serdata_from_iov::<T>}`

error[E0308]: mismatched types
   --> src/serdes.rs:797:22
    |
797 |         to_ser: Some(serdata_to_ser::<T>),
    |                      ^^^^^^^^^^^^^^^^^^^ expected `u32`, found `u64`
    |
    = note: expected fn pointer `unsafe extern "C" fn(_, u32, u32, _)`
                  found fn item `unsafe extern "C" fn(_, u64, u64, _) {serdata_to_ser::<T>}`

error[E0308]: mismatched types
   --> src/serdes.rs:798:26
    |
798 |         to_ser_ref: Some(serdata_to_ser_ref::<T>),
    |                          ^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `u64`
    |
    = note: expected fn pointer `unsafe extern "C" fn(_, u32, u32, _) -> _`
                  found fn item `unsafe extern "C" fn(_, u64, u64, _) -> _ {serdata_to_ser_ref::<T>}`

error[E0308]: mismatched types
   --> src/serdes.rs:804:21
    |
804 |         print: Some(print::<T>),
    |                     ^^^^^^^^^^ expected `u32`, found `u64`
    |
    = note: expected fn pointer `unsafe extern "C" fn(_, _, _, u32) -> u32`
                  found fn item `unsafe extern "C" fn(_, _, _, u64) -> u64 {print::<T>}`

Some errors have detailed explanations: E0308, E0560.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `cyclonedds-rs` due to 17 previous errors
pi@raspberrypi:~/Documents/cyclonedds-rs $

**Comment by sjames** [comment]
This should be fixed now.  The changes necessary to build for a 32bit target are done.  I've tested this by cross compiling with a Yocto SDK for armv7.
