### ISSUE TITLE
Performance and comparison 

### ISSUE THREAD

**Issue by fgadaleta** [sjames/cyclonedds-rs#3]
Hi Sojan, have you run some comparison with RustDDS and FastDDS?
How about compatibility and completeness wrt the open standard? 

Thanks

**Comment by BH1SCW** [comment]
> Hi Sojan, have you run some comparison with RustDDS and FastDDS? How about compatibility and completeness wrt the open standard?
> 
> Thanks

This is a really good question, I will wait for later update.
Thanks

**Comment by sjames** [comment]
> 

Hi @fgadaleta . 

At the time I started this, the RustDDS was in very early stages of development and I did not perform a comparison. 

My primary requirement was to have a C API that I could use to create a Rust binding easily.  FastDDS is a C++ API to the best of my knowledge and that went out of my list.

Another nice feature about CDDS is the ability to create your own serialization and deserialization hooks. This helps me avoid the IDL.  The CDDS folks have been very helpful in sorting out some of the issues I had. 

In the Sabaton platform, inspired by ROS, we use a middle-ware abstraction library that abstracts away the DDS implementation. The idea is that switching to another pub/sub technology can be painless in theory.  https://github.com/sabaton-rs/sabaton-mw .

At this time I don't really have a use-case for interoperability  between other implementations of DDS.  I haven't tried it out but based on what I read on the CycloneDDS issues,  interoperability is pretty decent at the wire protocol level, even though the API is not strictly DDS.

Regards,
Sojan

PS:  Sorry about the delay. I was out Sailing all last week.

**Comment by BH1SCW** [comment]
> > 
> 
> Hi @fgadaleta .
> 
> At the time I started this, the RustDDS was in very early stages of development and I did not perform a comparison.
> 
> My primary requirement was to have a C API that I could use to create a Rust binding easily. FastDDS is a C++ API to the best of my knowledge and that went out of my list.

Yeah, indeed

> 
> Another nice feature about CDDS is the ability to create your own serialization and deserialization hooks. This helps me avoid the IDL. The CDDS folks have been very helpful in sorting out some of the issues I had.

long time ago, I tried to use c macro to generate all kinds of data struct, it works but the code after expand was large.
> 
> In the Sabaton platform, inspired by ROS, we use a middle-ware abstraction library that abstracts away the DDS implementation. The idea is that switching to another pub/sub technology can be painless in theory. https://github.com/sabaton-rs/sabaton-mw .
> 
> At this time I don't really have a use-case for interoperability between other implementations of DDS. I haven't tried it out but based on what I read on the CycloneDDS issues, interoperability is pretty decent at the wire protocol level, even though the API is not strictly DDS.
> 
> Regards, Sojan
> 
> PS: Sorry about the delay. I was out Sailing all last week.

Sailing + Amateur Radio sounds cool! :)
