### ISSUE TITLE
failed to build, version mismatch

### ISSUE THREAD

**Issue by FranziDi** [sjames/cyclonedds-rs#9]
Compiling cyclonedds-sys v0.2.1
   Compiling cyclonedds-rs v0.6.5
error[E0609]: no field `iox_size` on type `cyclonedds_sys::ddsi_sertype`
   --> /home/usr/.cargo/registry/src/github.com-1ecc6299db9ec823/cyclonedds-rs-0.6.5/src/serdes.rs:126:29
    |
126 |                     sertype.iox_size = std::mem::size_of::<T>() as u32;
    |                             ^^^^^^^^ unknown field
    |
    = note: available fields are: `ops`, `serdata_ops`, `serdata_basehash`, `_bitfield_1`, `allowed_data_representation` ... and 5 others

error[E0609]: no field `iox_subscriber` on type `cyclonedds_sys::ddsi_serdata`
   --> /home/usr/.cargo/registry/src/github.com-1ecc6299db9ec823/cyclonedds-rs-0.6.5/src/serdes.rs:687:25
    |
687 |     if !serdata.serdata.iox_subscriber.is_null() {
    |                         ^^^^^^^^^^^^^^ unknown field
    |
    = note: available fields are: `ops`, `hash`, `refc`, `kind`, `type_` ... and 3 others

error[E0609]: no field `iox_subscriber` on type `cyclonedds_sys::ddsi_serdata`
   --> /home/usr/.cargo/registry/src/github.com-1ecc6299db9ec823/cyclonedds-rs-0.6.5/src/serdes.rs:688:62
    |
688 | ...t = serdata.serdata.iox_subscriber as *mut iox_sub_t;
    |                        ^^^^^^^^^^^^^^ unknown field
    |
    = note: available fields are: `ops`, `hash`, `refc`, `kind`, `type_` ... and 3 others

error[E0609]: no field `iox_chunk` on type `cyclonedds_sys::ddsi_serdata`
   --> /home/usr/.cargo/registry/src/github.com-1ecc6299db9ec823/cyclonedds-rs-0.6.5/src/serdes.rs:689:42
    |
689 |         let chunk = &mut serdata.serdata.iox_chunk;
    |                                          ^^^^^^^^^ unknown field
    |
    = note: available fields are: `ops`, `hash`, `refc`, `kind`, `type_` ... and 3 others

...

...
error[E0560]: struct `cyclonedds_sys::ddsi_serdata_ops` has no field named `from_iox_buffer`
    --> /home/usr/.cargo/registry/src/github.com-1ecc6299db9ec823/cyclonedds-rs-0.6.5/src/serdes.rs:1140:9
     |
1140 |         from_iox_buffer: Some(from_iox_buffer::<T>),
     |         ^^^^^^^^^^^^^^^ `cyclonedds_sys::ddsi_serdata_ops` does not have this field
     |
     = note: available fields are: `eqkey`, `get_size`, `from_ser`, `from_ser_iov`, `from_keyhash` ... and 10 others

Some errors have detailed explanations: E0560, E0609.
For more information about an error, try `rustc --explain E0560`.
error: could not compile `cyclonedds-rs` due to 14 previous errors

I am not sure where the version mismatch comes from. Do the versions of cyclonedds-rs (v0.6.5) and cyclonedds-sys (v0.2.1) from crates.io (used here) match the latest code pushed to github? The latest code pushed to github cyclonedds-sys seems to have the missing fields.

Thanks!
Best regards,
Franzi

**Comment by sjames** [comment]
Which version of cyclonedds and iceoryx have you installed on your machine?  This could be because you may have used the master branch of cyclonedds.

Please build and install the following versions of iceoryx and cyclonedds respectively.

- iceoryx https://github.com/eclipse-iceoryx/iceoryx version 2.0.2. (https://github.com/eclipse-iceoryx/iceoryx/commit/f756b7c99ddf714d05929374492b34c5c69355bb) Do not install any other version.
- cyclonedds 0.10.x branch (https://github.com/eclipse-cyclonedds/cyclonedds/commit/1be07de395e4ddf969db2b90328cdf4fb73e9a64)

There have been many changes to the internal cyclonedds API that this binding uses. The changes are still ongoing, so waiting for that to stabilize before supporting it.

Do let me know if this helps.  I just verified it.

**Comment by FranziDi** [comment]
Sorry for the late reply.
I was able to fix the problem now.

Besides the issue that I had used the wrong version of cyclonedds (thanks for your hint!),
cyclonedds did not find the dependency to iceoryx (in my development environment), so the switch "ENABLE_SHM" was set to OFF and the corresponding variables were not generated. Now it works!

**Comment by sjames** [comment]
> Sorry for the late reply. I was able to fix the problem now.
> 
> Besides the issue that I had used the wrong version of cyclonedds (thanks for your hint!), cyclonedds did not find the dependency to iceoryx (in my development environment), so the switch "ENABLE_SHM" was set to OFF and the corresponding variables were not generated. Now it works!

Thank you for the update!  Hope this project is useful for you!

**Comment by Titikshaaaa** [comment]
Hi FranziDi, I am also facing the same compilation errors as you. I wanted to ask if you are building CycloneDDS with Iceoryx, and if so, could you please share the flags you are setting? Thank you so much!
